In [1]:
import numpy as np
from sklearn.datasets import make_classification

In [5]:
from sklearn.model_selection import train_test_split

In [8]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

In [13]:
from sklearn.metrics import classification_report

In [2]:
#create an imbalance binary classification  dataset
X,y = make_classification(n_samples = 1000, n_features = 10, n_informative=2, n_redundant=8, weights = [0.9,0.1], flip_y=0, random_state=42)

In [3]:
np.unique(y, return_counts=True)

(array([0, 1]), array([900, 100]))

In [6]:
X

array([[-2.33224581, -1.73015228, -4.05388142, ...,  0.85612326,
        -3.13555024,  1.22003574],
       [ 0.78663065,  0.72655494,  1.07774555, ..., -0.32878979,
         0.66469403, -0.32691647],
       [ 1.4709666 ,  1.32562619,  2.08216446, ..., -0.60558465,
         1.33361742, -0.63083993],
       ...,
       [-2.78244158, -1.9136032 , -5.14120195, ...,  0.97924357,
        -4.15435048,  1.54457183],
       [-0.43118285, -0.76179492,  0.14539007, ...,  0.2819945 ,
         0.6344439 , -0.0358334 ],
       [-1.41528041, -1.09134101, -2.37613076, ...,  0.53112078,
        -1.78892693,  0.71585107]])

In [10]:
y

array([0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,

In [7]:
#Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, stratify=y, random_state = 42)

In [11]:
#Define the model hyperparameter
params = {
    "solver":'lbfgs',
    "max_iter":1000,
    "multi_class":"auto",
    "random_state":8888,
}

#Define the model
model = LogisticRegression(**params)
model.fit(X_train,y_train)



d:\a27_YEARS_OLD\mlflow_mlops\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='auto', random_state=8888)

In [12]:
#predict on the test set
y_pred = model.predict(X_test)

In [19]:
mlreport = classification_report(y_test,y_pred, output_dict=True)
mlreport

{'0': {'precision': 0.9456521739130435,
  'recall': 0.9666666666666667,
  'f1-score': 0.9560439560439561,
  'support': 270.0},
 '1': {'precision': 0.625,
  'recall': 0.5,
  'f1-score': 0.5555555555555556,
  'support': 30.0},
 'accuracy': 0.92,
 'macro avg': {'precision': 0.7853260869565217,
  'recall': 0.7333333333333334,
  'f1-score': 0.7557997557997558,
  'support': 300.0},
 'weighted avg': {'precision': 0.9135869565217392,
  'recall': 0.92,
  'f1-score': 0.9159951159951161,
  'support': 300.0}}

In [18]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       270
           1       0.62      0.50      0.56        30

    accuracy                           0.92       300
   macro avg       0.79      0.73      0.76       300
weighted avg       0.91      0.92      0.92       300



In [17]:
import mlflow

In [22]:
mlflow.set_experiment("first experiment")
mlflow.set_tracking_uri(uri='http://127.0.0.1:5000/')

with mlflow.start_run():
    mlflow.log_params(params)
    mlflow.log_metrics({
        'accuracy': mlreport['accuracy'],
        'recall_class_0': mlreport['0']['recall'],
        'recall_class_1': mlreport['1']['recall'],
        'f1_score_macro': mlreport['macro avg']['f1-score']
        
        })
    mlflow.sklearn.log_model(model, "Logistic Regression")

2024/09/04 11:44:37 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/09/04 11:44:37 INFO mlflow.tracking._tracking_service.client: 🏃 View run trusting-vole-52 at: http://127.0.0.1:5000/#/experiments/672332364106626237/runs/1c4d113131b6444da78d715a86ac75c7.
2024/09/04 11:44:37 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/672332364106626237.


In [23]:
# Experiment 1 :Train LogisticRegression

log_reg = LogisticRegression(C=1, solver='liblinear')
log_reg.fit(X_train, y_train)
y_pred_log_reg = log_reg.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       270
           1       0.62      0.50      0.56        30

    accuracy                           0.92       300
   macro avg       0.79      0.73      0.76       300
weighted avg       0.91      0.92      0.92       300



In [24]:
# Experiment 2: Train RandomForestClassifier

rf_clf = RandomForestClassifier(n_estimators=100, max_depth=None, random_state=42)
rf_clf.fit(X_train, y_train)
y_pred_rf_clf = rf_clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       270
           1       0.62      0.50      0.56        30

    accuracy                           0.92       300
   macro avg       0.79      0.73      0.76       300
weighted avg       0.91      0.92      0.92       300



In [26]:
# Experiment 3: Train XGBoost 

xgb_clf = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
xgb_clf.fit(X_train, y_train)
y_pred_xgb_clf = xgb_clf.predict(X_test)
print(classification_report(y_test,y_pred))


              precision    recall  f1-score   support

           0       0.95      0.97      0.96       270
           1       0.62      0.50      0.56        30

    accuracy                           0.92       300
   macro avg       0.79      0.73      0.76       300
weighted avg       0.91      0.92      0.92       300



Experiment 4: Handle class imbalance using SMOTETomek and then Train XGBoost

In [27]:
from imblearn.combine import SMOTETomek

In [28]:
smt = SMOTETomek(random_state=42)
X_smote, y_smote = smt.fit_resample(X, y)
X_train_smote, X_test_smote, y_train_smote, y_test_smote = train_test_split(X_smote, y_smote, test_size=0.3, stratify=y_smote, random_state = 42)
np.unique(y_train_smote, return_counts=True)

(array([0, 1]), array([613, 613]))

In [29]:
X_train_res , y_train_res = smt.fit_resample(X_train, y_train)
np.unique(y_train_res,return_counts=True)

(array([0, 1]), array([619, 619]))

In [30]:
xgb_clf = XGBClassifier(use_label_encoder = False, eval_metric="logloss")
xgb_clf.fit(X_train_res, y_train_res)
y_pred_xgb_clf = xgb_clf.predict(X_test)
print(classification_report(y_test, y_pred_xgb_clf))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       270
           1       0.81      0.83      0.82        30

    accuracy                           0.96       300
   macro avg       0.89      0.91      0.90       300
weighted avg       0.96      0.96      0.96       300



Track experiments using MLFLOW

In [32]:
models = [
    (
        "Logistic Regression",
        LogisticRegression(C=1, solver='liblinear'),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "Random Forest",
        RandomForestClassifier(n_estimators=100, max_depth=3, random_state=42),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "XGBClassifier",
        XGBClassifier(use_label_encoder=False, eval_metric='logloss'),
        (X_train, y_train),
        (X_test, y_test)
    ),
    (
        "XGBClassifier with SMOTETomek",
        XGBClassifier(use_label_encoder=False, eval_metric='logloss'), 
        (X_train_res, y_train_res),
        (X_test, y_test)
    )

]

In [34]:
reports = []

for model_name, model, train_set, test_set in models:
    X_train = train_set[0]
    y_train = train_set[1]
    X_test = train_set[0]
    y_test = train_set[1]

    model.fit(X_train,y_train)
    y_pred = model.predict(X_test) 
    report = classification_report(y_test, y_pred , output_dict=True)
    reports.append(report)   

In [2]:
import mlflow
import mlflow.sklearn
import mlflow.xgboost

In [41]:
#Initiate Mlflow
mlflow.set_experiment("Anomaly Detection")
mlflow.set_tracking_uri('http://127.0.0.1:5000/')

for i , element in enumerate(models):
    model_name = element[0]
    model = element[1]
    report = reports[i]

    with mlflow.start_run(run_name=model_name):
        mlflow.log_param("model", model_name)
        mlflow.log_metric("accuracy", report["accuracy"])
        # mlflow.log_metric("precision", report["precision"])
        mlflow.log_metric("recall_ckass_1", report['1']["recall"])
        mlflow.log_metric("recall_ckass_0", report['0']["recall"])
        mlflow.log_metric("f1_score_macro", report['macro avg']["f1-score"])

        if "XGBClassifier" in model_name:
            mlflow.xgboost.log_model(model, "model")
        else:
            mlflow.sklearn.log_model(model, "model")
        

2024/09/04 17:24:27 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/09/04 17:24:27 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/433191269776832543/runs/c459c32c600b44b7b27ec41c8661445b.
2024/09/04 17:24:27 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/433191269776832543.
2024/09/04 17:24:30 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/09/04 17:24:30 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/433191269776832543/runs/cb60d66fde06495f806c7f7b38fe0246.
2024/09/04 17:24:30 INFO mlflow.tracking._tracking_service.client: 🧪 View exp

Register the model 

In [1]:
model_name = "XGB-Smote"
run_id = input("Enter Run Id:")


In [3]:
model_name = "XGB-Smote"
run_id = "f17a837afe234e04bd7882fcb1045ace"
model_uri = f"runs:/{run_id}/{model_name}"

result = mlflow.register_model(
    model_uri, model_name
)

Registered model 'XGB-Smote' already exists. Creating a new version of this model...
Created version '2' of model 'XGB-Smote'.


load the model

In [11]:
mlflow.set_tracking_uri('http://127.0.0.1:5000')

http://127.0.0.1:5000/#/models/XGB-Smote/versions/1

In [17]:
model_name = "XGB-Smote"
model_version = 1
# model_uri = f"models:/{model_name}/versions/{model_version}"
model_uri = f"models:/{model_name}@challenger"


loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

MlflowException: The following failures occurred while downloading one or more artifacts from http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote:
##### File  #####
API request to http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote/ failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote/ (Caused by ResponseError('too many 500 error responses'))

In [16]:
dev_model_uri = f"models:/{model_name}@challenger"
prod_model = "anamoly-detection-prod"

client = mlflow.MlflowClient()
client.copy_model_version(src_model_uri=dev_model_uri,dst_name=prod_model)

Successfully registered model 'anamoly-detection-prod'.
Copied version '1' of model 'XGB-Smote' to version '1' of model 'anamoly-detection-prod'.


<ModelVersion: aliases=[], creation_timestamp=1725457887196, current_stage='None', description='', last_updated_timestamp=1725457887196, name='anamoly-detection-prod', run_id='f17a837afe234e04bd7882fcb1045ace', run_link='', source='models:/XGB-Smote/1', status='READY', status_message='', tags={}, user_id='', version='1'>

In [19]:
prod_model = "anamoly-detection-prod"
model_version = 1
# model_uri = f"models:/{model_name}/versions/{model_version}"
model_uri = f"models:/{prod_model}@champion"


loaded_model = mlflow.xgboost.load_model(model_uri)
y_pred = loaded_model.predict(X_test)
y_pred[:4]

MlflowException: The following failures occurred while downloading one or more artifacts from http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote:
##### File  #####
API request to http://127.0.0.1:5000/api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote/ failed with exception HTTPConnectionPool(host='127.0.0.1', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/433191269776832543/f17a837afe234e04bd7882fcb1045ace/artifacts/XGB-Smote/ (Caused by ResponseError('too many 500 error responses'))